## Welcome to Scikit Learn

In [1]:
## Get the data ready
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 
heart_disease=pd.read_csv("heart-disease.csv")

In [2]:
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [3]:
x=heart_disease.drop("target",axis=1)
y=heart_disease["target"]

In [4]:
## Choose the right model
from sklearn.ensemble import RandomForestClassifier

In [5]:
clf=RandomForestClassifier(n_estimators=100)

In [6]:
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [9]:
clf.fit(x_train,y_train)

RandomForestClassifier()

In [10]:
y_preds=clf.predict(x_test)

In [11]:
y_preds

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1])

In [12]:
## Evaluate

In [13]:
clf.score(x_train,y_train)

1.0

In [14]:
clf.score(x_test,y_test)

0.7540983606557377

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [16]:
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.71      0.83      0.76        29
           1       0.81      0.69      0.75        32

    accuracy                           0.75        61
   macro avg       0.76      0.76      0.75        61
weighted avg       0.76      0.75      0.75        61

In [17]:
print(confusion_matrix(y_test,y_preds))

[[24  5]
 [10 22]]

In [18]:
print(accuracy_score(y_test,y_preds))

0.7540983606557377

In [19]:
## imprpoving the model

In [20]:
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"trying model {i}")
    clf = RandomForestClassifier(n_estimators=i).fit(x_train, y_train)
    print(f"model set: {clf.score(x_test, y_test) * 100:.2f}%")
    print(" ")

trying model 10
model set: 70.49%

trying model 20
model set: 73.77%

trying model 30
model set: 73.77%

trying model 40
model set: 75.41%

trying model 50
model set: 72.13%

trying model 60
model set: 75.41%

trying model 70
model set: 77.05%

trying model 80
model set: 73.77%

trying model 90
model set: 75.41%

In [21]:
##save model

In [22]:
import pickle

In [23]:
pickle.dump(clf,open("randomForest1.pkl","wb"))

In [24]:
loaded_model=pickle.load(open("randomForest1.pkl","rb"))

In [25]:
loaded_model.score(x_test,y_test)

0.7540983606557377

## Getting data Ready

In [26]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [27]:
x=heart_disease.drop("target",axis=1)

In [28]:
y=heart_disease["target"]

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [31]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

## Make sure that it is numbered

In [32]:
car_sales=pd.read_csv("car-sales.csv")

In [33]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [34]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [35]:
x=car_sales.drop("Price",axis=1)
car_sales["Price"] = car_sales["Price"].str.replace("[$,]", "", regex=True).astype(float)
y=car_sales["Price"]

In [36]:
# ## split into training and test
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()
# model.fit(x_train,y_train)
# model.score(x_test,y_test)
# ## The above will give error which we will resolve below

In [37]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White         150043      4   4000.0
1   Honda    Red          87899      4   5000.0
2  Toyota   Blue          32549      3   7000.0
3     BMW  Black          11179      5  22000.0
4  Nissan  White         213095      4   3500.0

In [38]:
## Build machine learning model
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_features)],
                              remainder="passthrough")
transformed_x=transformer.fit_transform(x)
transformed_x
pd.DataFrame(transformed_x)

    0    1    2    3    4    5    6    7    8    9    10   11        12
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  150043.0
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   87899.0
2  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   32549.0
3  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   11179.0
4  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  213095.0
5  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0   99213.0
6  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   45698.0
7  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   54738.0
8  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   60000.0
9  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   31600.0

In [39]:
np.random.seed(49)
x_train,x_test,y_train,y_test=train_test_split(transformed_x,
                                               y,
                                               test_size=0.2)
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.35196983687288397

## What is missing values are present in the data

In [40]:
## Fill them with some values (imputation)
## Remove the samples with missing data altogether

In [41]:
car_sales_missing=pd.read_csv("car-sales-missing-data.csv")

In [42]:
## You will get error if you try to convert the above data into numbers because of missing values so remediate it first
car_sales_missing.isna().sum()

Make        1
Colour      1
Odometer    4
Doors       1
Price       2
dtype: int64

In [43]:
car_sales_missing["Make"] = car_sales_missing["Make"].fillna("missing")
car_sales_missing["Colour"] = car_sales_missing["Colour"].fillna("missing")
car_sales_missing["Odometer"] = car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean())
car_sales_missing["Doors"] = car_sales_missing["Doors"].fillna(4)
car_sales_missing.dropna(inplace=True)

In [44]:
x=car_sales_missing.drop("Price",axis=1)
car_sales_missing["Price"] = car_sales_missing["Price"].str.replace("[$,]", "", regex=True).astype(float)
y=car_sales_missing["Price"]

In [45]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_features)],
                              remainder="passthrough")
transformed_x=transformer.fit_transform(x)
transformed_x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 32 stored elements and shape (8, 15)>

In [46]:
np.random.seed(67)
x_train,x_test,y_train,y_test=train_test_split(transformed_x,
                                               y,
                                               test_size=0.2)
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.6448553401046475

## Fill missing values with scikit-learn(Always prioritize this)

In [47]:
car_missing=pd.read_csv("car-sales-extended-missing-data.csv")

In [48]:
car_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [49]:
car_missing.dropna(subset=["Price"],inplace=True)

In [50]:
car_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [51]:
## split into x and y
x=car_missing.drop("Price",axis=1)
y=car_missing["Price"]

In [52]:
## Fill missing values with scikit learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [53]:
## Fill categorical values with 'missing' and numerical with 'mean'
cat_imputer=SimpleImputer(strategy="constant",
                          fill_value="missing")
door_imputer=SimpleImputer(strategy="constant",
                           fill_value=4)
num_imputer=SimpleImputer(strategy="mean")

In [54]:
## Define
cat_features=["Make","Colour"]
door_features=["Doors"]
num_features=["Odometer (KM)"]

In [55]:
## Create an imputer(something that fills missing data)
imputer=ColumnTransformer([
    ("cat_imputer",cat_imputer,cat_features),
    ("door_imputer",door_imputer,door_features),
    ("num_imputer",num_imputer,num_features)
])
filled_x=imputer.fit_transform(x)
filled_x

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], shape=(950, 4), dtype=object)

In [56]:
car_sales_filled=pd.DataFrame(filled_x,
                              columns=["Make","Colour","Doors","Odometer (KM)"])

In [57]:
car_sales_filled.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [58]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_features)],
                              remainder="passthrough")
transformed_x=transformer.fit_transform(car_sales_filled)
transformed_x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3800 stored elements and shape (950, 15)>

In [59]:
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(transformed_x,
                                               y,
                                               test_size=0.2)
model=RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.21990196728583944

In [60]:
len(car_sales_filled)

950

## In this section we will try to check how we can choose the right model

In [61]:
from sklearn.datasets import fetch_california_housing
housing=fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [62]:
housing_df=pd.DataFrame(housing["data"],columns=housing["feature_names"])
housing_df["MedHouseVal"]=housing["target"]
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [63]:
housing_df["target"]=housing["target"]
housing_df=housing_df.drop("MedHouseVal",axis=1)
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [64]:
from sklearn.linear_model import Ridge
np.random.seed(42)
x=housing_df.drop("target",axis=1)
y=housing_df["target"]
x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2)
model=Ridge()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.5758549611440126

In [65]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)
x=housing_df.drop("target",axis=1)
y=housing_df["target"]
x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2)
model=RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.8059809073051385

## Choosing the best estimator/model/algorithm for Classification

In [66]:
heart_disease=pd.read_csv("heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [67]:
from sklearn.svm import LinearSVC
np.random.seed(42)
x=heart_disease.drop("target",axis=1)
y=heart_disease["target"]
x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2)
model=LinearSVC()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.8688524590163934

In [68]:
heart_disease["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [69]:
from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)
x=heart_disease.drop("target",axis=1)
y=heart_disease["target"]
x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2)
model=RandomForestClassifier()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.8524590163934426

## 3.2 Make predictions with predict()

In [70]:
x_test.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
179,57,1,0,150,276,0,0,112,1,0.6,1,1,1
228,59,1,3,170,288,0,0,159,0,0.2,1,0,3
111,57,1,2,150,126,1,1,173,0,0.2,2,1,3
246,56,0,0,134,409,0,0,150,1,1.9,1,2,3
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2

In [71]:
model.predict(x_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [72]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [73]:
y_preds=model.predict(x_test)
np.mean(y_preds==y_test)

np.float64(0.8524590163934426)

In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_preds)

0.8524590163934426

## Make prediction with predict_proba()

In [75]:
model.predict_proba(x_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [76]:
model.predict(x_test[:5])

array([0, 1, 1, 0, 1])

## Using Predict on Regresssion

In [77]:
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [78]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)
x=housing_df.drop("target",axis=1)
y=housing_df["target"]
x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2)
model=RandomForestRegressor()
model.fit(x_train,y_train)
y_preds=model.predict(x_test)

In [79]:
y_preds[:10]

array([0.49058  , 0.75989  , 4.9350165, 2.55864  , 2.33461  , 1.6580801,
       2.34237  , 1.66708  , 2.5609601, 4.8519781])

In [80]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

In [81]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_preds)

0.3270458119670544

## 4) Evaluating a model
There are 3 steps:
score()
scoring()
Probelm-specific-metric

In [82]:
#4.2 Scoring

In [83]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)
x=heart_disease.drop("target",axis=1)
y=heart_disease["target"]
x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2)
model=RandomForestClassifier()
model.fit(x_train,y_train)
#model.score(x_test,y_test)
#cross_val_score(model,x,y,cv=5)
np.random.seed(42)
model_single_score=model.score(x_test,y_test)
model_cross_value_score=np.mean(cross_val_score(model,x,y,cv=5))
model_single_score,model_cross_value_score

(0.8524590163934426, np.float64(0.8248087431693989))

## 4.2.1 Classification model evaluation metrics 
1) Accuracy
2) Area under ROC curve
3) Confusion metrics
4) Classification report

In [89]:
#1) Accuracy
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)
x=heart_disease.drop("target",axis=1)
y=heart_disease["target"]
model=RandomForestClassifier()
cross_val_score=cross_val_score(model,x,y,cv=5)
np.mean(cross_val_score*100)

np.float64(82.48087431693988)

In [96]:
#2) Area under receiver operating characteristic curve (AUC/ROC)
#True positive=model predicts 1 when the truth is 1
#False positive=model predicts 1 when the truth is 0
#ROC curve are a comparison of a model's TPR versus model's FPR
from sklearn.metrics import roc_curve
model.fit(x_train,y_train)
y_probs=model.predict_proba(x_test)
y_probs_positive=y_probs[:,1]
fpr,tpr,thresholds=roc_curve(y_test,y_probs_positive)
fpr

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.03448276,
       0.03448276, 0.10344828, 0.13793103, 0.13793103, 0.13793103,
       0.24137931, 0.27586207, 0.37931034, 0.44827586, 0.48275862,
       0.5862069 , 0.65517241, 0.65517241, 0.86206897, 1.        ])