## Welcome to Scikit Learn

In [1]:
## Get the data ready
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 
heart_disease=pd.read_csv("heart-disease.csv")

In [2]:
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [3]:
x=heart_disease.drop("target",axis=1)
y=heart_disease["target"]

In [4]:
## Choose the right model
from sklearn.ensemble import RandomForestClassifier

In [5]:
clf=RandomForestClassifier(n_estimators=100)

In [6]:
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [9]:
clf.fit(x_train,y_train)

RandomForestClassifier()

In [10]:
y_preds=clf.predict(x_test)

In [11]:
y_preds

array([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1])

In [12]:
## Evaluate

In [13]:
clf.score(x_train,y_train)

1.0

In [14]:
clf.score(x_test,y_test)

0.8360655737704918

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [16]:
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83        29
           1       0.84      0.84      0.84        32

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61

In [17]:
print(confusion_matrix(y_test,y_preds))

[[24  5]
 [ 5 27]]

In [18]:
print(accuracy_score(y_test,y_preds))

0.8360655737704918

In [19]:
## imprpoving the model

In [20]:
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"trying model {i}")
    clf = RandomForestClassifier(n_estimators=i).fit(x_train, y_train)
    print(f"model set: {clf.score(x_test, y_test) * 100:.2f}%")
    print(" ")

trying model 10
model set: 80.33%

trying model 20
model set: 81.97%

trying model 30
model set: 80.33%

trying model 40
model set: 83.61%

trying model 50
model set: 81.97%

trying model 60
model set: 80.33%

trying model 70
model set: 80.33%

trying model 80
model set: 78.69%

trying model 90
model set: 83.61%

In [21]:
##save model

In [22]:
import pickle

In [23]:
pickle.dump(clf,open("randomForest1.pkl","wb"))

In [24]:
loaded_model=pickle.load(open("randomForest1.pkl","rb"))

In [25]:
loaded_model.score(x_test,y_test)

0.8360655737704918

## Getting data Ready

In [26]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [27]:
x=heart_disease.drop("target",axis=1)

In [28]:
y=heart_disease["target"]

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [31]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

## Make sure that it is numbered

In [32]:
car_sales=pd.read_csv("car-sales.csv")

In [33]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [36]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [38]:
x=car_sales.drop("Price",axis=1)
y=car_sales["Price"]

In [40]:
## split into training and test
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [46]:
## Build machine learning model
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)
from sklearn.preprocessing import oneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features=["Make","Colour","Doors"]
one_hot=oneHotEncoder()
transformer=ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_features)]
                              remainder="passthrough")

ValueError: could not convert string to float: 'Honda'